# Generated by Django 5.1.3 on 2025-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip Hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('country', 'Country'), ('reggae', 'Reggae'), ('other', 'Other')], default='other', max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(upload_to='song_files/')),
                ('is_famous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
